global:
  image:
    repository: jaylenwang
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080
  mysql:
    host: "mysql"
    port: "3306"
    database: "ts"
    user: "root"
    password: "yourpassword" 
  monitoring: "opentelemetry"

opentelemetry:
  enabled: true
  image: otel/autoinstrumentation-java:latest

services:
  tsAdminBasicInfoService:
    name: ts-admin-basic-info-service-jaeger
    secretRef: ts-admin-basic-info-service-jaeger
  tsAdminOrderService:
    name: ts-admin-order-service-jaeger
    secretRef: ts-admin-order-service-jaeger
  tsAdminRouteService:
    name: ts-admin-route-service-jaeger
    secretRef: ts-admin-route-service-jaeger
  tsAdminTravelService:
    name: ts-admin-travel-service-jaeger
    secretRef: ts-admin-travel-service-jaeger
  tsAdminUserService:
    name: ts-admin-user-service-jaeger
    secretRef: ts-admin-user-service-jaeger
  tsAssuranceService:
    name: ts-assurance-service-jaeger
    secretRef: ts-assurance-service-jaeger
  tsAuthService:
    name: ts-auth-service-jaeger
    secretRef: ts-auth-service-jaeger
  tsAvatarService:
    name: ts-avatar-service-jaeger
    secretRef: ts-avatar-service-jaeger
    language: python
  tsBasicService:
    name: ts-basic-service-jaeger
    secretRef: ts-basic-service-jaeger
  tsCancelService:
    name: ts-cancel-service-jaeger
    secretRef: ts-cancel-service-jaeger
  tsConfigService:
    name: ts-config-service-jaeger
    secretRef: ts-config-service-jaeger
  tsConsignPriceService:
    name: ts-consign-price-service-jaeger
    secretRef: ts-consign-price-service-jaeger
  tsConsignService:
    name: ts-consign-service-jaeger
    secretRef: ts-consign-service-jaeger
  tsContactsService:
    name: ts-contacts-service-jaeger
    secretRef: ts-contacts-service-jaeger
  tsDeliveryService:
    name: ts-delivery-service-jaeger
    secretRef: ts-delivery-service-jaeger
  tsExecuteService:
    name: ts-execute-service-jaeger
    secretRef: ts-execute-service-jaeger
  tsFoodDeliveryService:
    name: ts-food-delivery-service-jaeger
    secretRef: ts-food-delivery-service-jaeger
  tsFoodService:
    name: ts-food-service-jaeger
    secretRef: ts-food-service-jaeger
  tsGatewayService:
    name: ts-gateway-service-jaeger
    secretRef: ts-gateway-service-jaeger
  tsInsidePaymentService:
    name: ts-inside-payment-service-jaeger
    secretRef: ts-inside-payment-service-jaeger
  tsNewsService:
    name: ts-news-service-jaeger
    secretRef: ts-news-service-jaeger
    language: golang
  tsNotificationService:
    name: ts-notification-service-jaeger
    secretRef: ts-notification-service-jaeger
  tsOrderOtherService:
    name: ts-order-other-service-jaeger
    secretRef: ts-order-other-service-jaeger
  tsOrderService:
    name: ts-order-service-jaeger
    secretRef: ts-order-service-jaeger
  tsPaymentService:
    name: ts-payment-service-jaeger
    secretRef: ts-payment-service-jaeger
  tsPreserveOtherService:
    name: ts-preserve-other-service-jaeger
    secretRef: ts-preserve-other-service-jaeger
  tsPreserveService:
    name: ts-preserve-service-jaeger
    secretRef: ts-preserve-service-jaeger
  tsPriceService:
    name: ts-price-service-jaeger
    secretRef: ts-price-service-jaeger
  tsRebookService:
    name: ts-rebook-service-jaeger
    secretRef: ts-rebook-service-jaeger
  tsRoutePlanService:
    name: ts-route-plan-service-jaeger
    secretRef: ts-route-plan-service-jaeger
  tsRouteService:
    name: ts-route-service-jaeger
    secretRef: ts-route-service-jaeger
  tsSeatService:
    name: ts-seat-service-jaeger
    secretRef: ts-seat-service-jaeger
  tsSecurityService:
    name: ts-security-service-jaeger
    secretRef: ts-security-service-jaeger
  tsStationFoodService:
    name: ts-station-food-service-jaeger
    secretRef: ts-station-food-service-jaeger
  tsStationService:
    name: ts-station-service-jaeger
    secretRef: ts-station-service-jaeger
  tsTicketOfficeService:
    name: ts-ticket-office-service-jaeger
    secretRef: ts-ticket-office-service-jaeger
    language: javascript
  tsTrainFoodService:
    name: ts-train-food-service-jaeger
    secretRef: ts-train-food-service-jaeger
  tsTrainService:
    name: ts-train-service-jaeger
    secretRef: ts-train-service-jaeger
  tsTravelPlanService:
    name: ts-travel-plan-service-jaeger
    secretRef: ts-travel-plan-service-jaeger
  tsTravelService:
    name: ts-travel-service-jaeger
    secretRef: ts-travel-service-jaeger
  tsTravel2Service:
    name: ts-travel2-service-jaeger
    secretRef: ts-travel2-service-jaeger
  tsUiDashboard:
    name: ts-ui-dashboard-jaeger
    secretRef: ts-ui-dashboard-jaeger
    type: NodePort
    nodePort: 30080
  tsUserService:
    name: ts-user-service-jaeger
    secretRef: ts-user-service-jaeger
  tsVerificationCodeService:
    name: ts-verification-code-service-jaeger
    secretRef: ts-verification-code-service-jaeger
  tsVoucherService:
    name: ts-voucher-service-jaeger
    secretRef: ts-voucher-service-jaeger
    language: python
  tsWaitOrderService:
    name: ts-wait-order-service-jaeger
    secretRef: ts-wait-order-service-jaeger