# Valid values are "daemonset", "deployment", and "statefulset".
mode: "deployment"

presets:
  kubernetesEvents:
    enabled: true
  clusterMetrics:
    enabled: true

image:
  repository: otel/opentelemetry-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

command:
  name: otelcol

configMap:
  create: true

config:
  exporters:
    otlp:
      endpoint: "jaeger-collector.monitoring:4317"
      tls:
        insecure: true
    logging:
      verbosity: detailed
  processors:
    batch:
      timeout: 5s
      send_batch_size: 100000
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: kube-prom-exporter
            scrape_interval: 10s
            static_configs:
              - targets:
                - prometheus-stack-prometheus-node-exporter.monitoring:9100
                - prometheus-stack-kube-state-metrics.monitoring:8080
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
    pipelines:
      logs: 
        exporters:
          - logging
          - otlp
        processors:
          - batch
        receivers:
          - otlp
      metrics: 
        exporters:
          - logging
          - otlp
        processors:
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - otlp
        processors:
          - batch
        receivers:
          - otlp